/**
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* PullRequestInfo contains information about a PR, like its PR and Build numbers
*/
export interface PullRequestInfo {
    'lastBuildNumberForCommit'?: string;
    'pullRequestNumber'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "lastBuildNumberForCommit",
            "baseName": "lastBuildNumberForCommit",
            "type": "string"
        },
        {
            "name": "pullRequestNumber",
            "baseName": "pullRequestNumber",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PullRequestInfo.attributeTypeMap;
    }
}

